import {
  AlertTriangle,
  Boxes,
  PackageCheck,
  RotateCcw,
  ScanLine,
  Truck,
  Waypoints,
} from 'lucide-react'

export const MODULE_CATALOG = [
  {
    code: 'dropscan',
    name: 'DropScan',
    shortName: 'DropScan',
    tagline: 'Escaneo de guias',
    description: 'Registro en tiempo real de guias, control de tarimas, operadores con PIN y alertas de duplicados.',
    landingDescription: 'Registra guias en tiempo real con validacion automatica de duplicados. Control de tarimas, sesiones de escaneo y reportes de productividad.',
    icon: ScanLine,
    color: 'text-blue-400',
    bg: 'bg-blue-500/10',
    border: 'border-blue-500/20',
    family: 'core',
    limitKey: 'guide_limit',
    unit: 'guias',
  },
  {
    code: 'surtido',
    name: 'Surtido WMS',
    shortName: 'Surtido',
    tagline: 'Ordenes de salida',
    description: 'Asignacion, rastreo y validacion de OBCs desde la liberacion hasta el cierre operativo.',
    landingDescription: 'Asigna, rastrea y valida ordenes de salida (OBCs) desde Google Sheets hasta el cierre. Control de surtidores y discrepancias en tiempo real.',
    icon: Truck,
    color: 'text-purple-400',
    bg: 'bg-purple-500/10',
    border: 'border-purple-500/20',
    family: 'core',
    limitKey: 'surtido_limit',
    unit: 'ordenes',
  },
  {
    code: 'inventario',
    name: 'Inventario',
    shortName: 'Inventario',
    tagline: 'Control de stock',
    description: 'Conteos, escaneo por celda, rastreo de cajas y visibilidad operativa del stock en bodega.',
    landingDescription: 'Sesiones de conteo con escaneo de barcodes, localizacion de cajas por celda, reportes de disponibilidad y exportacion a Excel.',
    icon: Boxes,
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/20',
    family: 'core',
    limitKey: 'inventario_limit',
    unit: 'escaneos',
  },
  {
    code: 'devoluciones',
    name: 'Devoluciones',
    shortName: 'Devoluciones',
    tagline: 'Entradas y salidas de retorno',
    description: 'Recepcion, clasificacion y trazabilidad de mercancia devuelta con evidencia y movimientos de inventario.',
    landingDescription: 'Registra, clasifica y da seguimiento a mercancia devuelta con trazabilidad completa: SKU, embalaje, evidencia fotografica y movimientos de inventario.',
    icon: RotateCcw,
    color: 'text-amber-400',
    bg: 'bg-amber-500/10',
    border: 'border-amber-500/20',
    family: 'core',
    limitKey: 'devoluciones_limit',
    unit: 'entradas',
  },
  {
    code: 'recepcion',
    name: 'Recepcion',
    shortName: 'Recepcion',
    tagline: 'Ingreso y validacion inbound',
    description: 'Ordenes inbound, listas de recepcion, validacion de cajas, novedades y escaneo por ubicacion.',
    landingDescription: 'Orquesta el ingreso inbound con ordenes, lineas, validacion por escaneo, novedades y listas de recepcion listas para piso.',
    icon: PackageCheck,
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/20',
    family: 'advanced',
  },
  {
    code: 'despacho',
    name: 'Despacho',
    shortName: 'Despacho',
    tagline: 'Cierre de folios y salida',
    description: 'Folios de salida, agenda, consolidacion y control del cierre final de despacho.',
    landingDescription: 'Gestiona folios, agenda de salida y validacion final para despachar con control de tiempos, cajas y evidencias.',
    icon: Waypoints,
    color: 'text-fuchsia-400',
    bg: 'bg-fuchsia-500/10',
    border: 'border-fuchsia-500/20',
    family: 'advanced',
  },
  {
    code: 'anormalidades',
    name: 'Anormalidades',
    shortName: 'Anormalidades',
    tagline: 'Incidencias y mejora continua',
    description: 'Registro de incidencias, niveles SLA, tableros de carga y vinculacion con mejoras operativas.',
    landingDescription: 'Centraliza incidencias, SLAs, responsables y acciones de mejora para cerrar problemas operativos con trazabilidad.',
    icon: AlertTriangle,
    color: 'text-rose-400',
    bg: 'bg-rose-500/10',
    border: 'border-rose-500/20',
    family: 'advanced',
  },
]

export const ALL_MODULE_CODES = MODULE_CATALOG.map(module => module.code)
